### ISSUE TITLE
Produits et listings pas modifiable en front

### ISSUE THREAD

**Issue by dabrokezz** [AliceChiappero/test#15]
Hello,
On a de nouveau le pb lié au cache (si mes souvenirs sont bons) où les listings et les produits apparaissent en page dans le menu haut noir et donc qd on ne peut plus modifier par le front, ce qui est bcp moins pratique 
<img width=\"1385\" alt=\"Capture d’écran 2024-10-08 à 14 55 44\" src=\"https://github.com/user-attachments/assets/b0bc432a-dc5f-4137-ae02-e479df23d8e8\">

**Comment by AliceChiappero** [comment]
lié au #13

**Comment by dabrokezz** [comment]
hum...
Bon ca venait d'un pb de listing pro vs les nouvelles normes de mise en cache ESI (ca permet de mettre certaines parties des pages en cache et d'autres pas)
sauf que listing pro désactiver ce concept sur la barre d'amin et celle ci etait mise en cache du coup ct tjs le meme lien de modification (l'accueil) au lieu de la page courante
Relouuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu 
![Image](https://github.com/user-attachments/assets/c9cee349-ce8a-4fb0-96ee-ad6c7b781586)
![Image](https://github.com/user-attachments/assets/487a983c-d178-4461-9446-cd01ad39f7e2)
![Image](https://github.com/user-attachments/assets/999171f1-73b4-4910-b45e-7d2d685e1ac6)
