### ISSUE TITLE
Stripe et autres paiements

### ISSUE THREAD

**Issue by enileda84** [AliceChiappero/test#19]
Stripe semble ne pas fonctionner mais j'ai comme message d'erreur que la banque a rejeté pour défaut d'authentification. Et de fait, je n'ai pas eu la demande de confirmation sur mon appli que je reçois habituellement pour chaque paiement. Je viens d'interroger ma banque, j'attends leur réponse, mais le problème vient peut-être du site ?!

D'autre part, pourrait-on configurer un paiement par Paypal, ou encoie mieux, par carte bancaire ?

**Comment by manu-macymed** [comment]
@enileda84 Juste pour qu'on puisse bien gérer l'outil, il faut absolument l'assigner à un projets sinon il ne sera pas visible dans le tableau de bord des tickets et on ne pourra pas le suivre. Donc passer par le projet pour créer les tickets est plus simple.

Ensuite, là il y a 2 tickets pour 1 demande ce qui n'est pas bon car on va avancer sur une tache et on ne pourra jamais la clore tant que l'autre ne sera pas fini.

Je vais clore ce ticket et en créer 2 autres.
