### ISSUE TITLE
User Switching

### ISSUE THREAD

**Issue by dabrokezz** [AliceChiappero/test#22]
Pouvoir se connecter en tant qu'un utilisateur

**Comment by dabrokezz** [comment]
Depuis
https://www.idees-piscine.com/wp-admin/users.php

![Image](https://github.com/user-attachments/assets/cd367e22-9e47-4b94-9146-d143a7fbcb9e)

Quand on survol un utilisateur, il y a un menu qui s'affiche "se connecter en tant que"
Si l'utilisateur a le role admin, on va rester dans l'admin
Sinon on est redirigé vers le front
Depuis le front, il faut peut etre faire un refresh de la page pour que ce soit actif

**Comment by AliceChiappero** [comment]
@dabrokezz j'ai cliqué sur Se connecter en tant que ds le BO et ca me dit ca comme message
![Image](https://github.com/user-attachments/assets/d5bc591a-8e68-4c81-a8db-8ea7680f2506)

**Comment by AliceChiappero** [comment]
@dabrokezz ah ca y est ca marche en fait, en réouvrant un nouvel onglet et en me connectant à Idées Piscine, ca m'a switché sur le profil que j'avais choisi dc je passe dans Done
