### ISSUE TITLE
Problème de typo sur le site quand pas loggé

### ISSUE THREAD

**Issue by enileda84** [AliceChiappero/test#23]

**Comment by enileda84** [comment]
Quand on n'est pas loggé, cafouillage à l'ouverture du site + problème de typos un peu partout

**Comment by manu-macymed** [comment]
Pas de souci de mon coté : https://idees-piscine.com/pb-home.mp4

**Comment by enileda84** [comment]
Effectivement le problème a disparu !

**Comment by enileda84** [comment]
Hello, le problème persiste. Non loggé, les typos sont vraiment moches, et en plus petites. Pendant une visio avec une cliente, elle m'a partagé son écran et c'était pareil. Sur mon tel c'est pareil. Est-ce qu'on ne pourrait pas nettoyer le code qui avait été ajouté pour modifier la typo, et retourner à la typo prévue par le thème ? Même si elle est un peu petite, elle est quand même mieux que ce qu'on a là. Si vous avez le temps de regarder un de ces jours ?

**Comment by manu-macymed** [comment]
Alors je  ne comprends vraiment pas car j'ai pas ça chez moi, que ça soit avec chrome, en navigation privée ou non, avec firefox alors que je ne l'utilise jamais.
Pas de nettoyage possible car je n'ai pas changé la typo sur le site, c'est celle de listingpro. Incompréhensible du coup.
Vous utilisez quel navigateur ? Mac ou Windows ?

Faudrait qu'on arrive à reproduire le problème

**Comment by enileda84** [comment]
Mac sur chrome et sur Safari et Iphone
