### ISSUE TITLE
Bug recherche annuaire - Urgent

### ISSUE THREAD

**Issue by AliceChiappero** [AliceChiappero/test#24]
Hello @dabrokezz @manu-macymed , je viens de parler à un futur client (hopefully) qui m'a fait part d'un bug dans l'annuaire , voilà le chemin utilisé : page d'accueil > dans barre de recherche Quoi a selectionné Equipement > donc elle arrive là : https://www.idees-piscine.com/listing-category/equipement/
et quand on coche sur la gauche par ex Adhérent FPP, ca mouline , voir video : https://app.usebubbles.com/kx56XLVuVhm76J4ZdKrP1
Si vous pouvez jeter un oeil, merci !

**Comment by manu-macymed** [comment]
Salut
C'est long mais ça fonctionne de mon coté.
Après, s'il y a un dysfonctionnement sur listingpro, je pense que le plus simple est d'ouvrir un ticket chez eux directement car ils seront plus aptes à corriger le pb.
Mais là ça fonctionne chez moi : https://idees-piscine.com/listing-ideep.mp4

**Comment by AliceChiappero** [comment]
Hello, alors le problème c'est que les utilisateurs ne sont pas en navigation privée...tu as testé pas en navigation privée ? pcq ca ne marche pas donc compliqué d'expliquer à mon client qu'il faut se mettre en navigation privée pour que ca marche...je vais essayer de retrouver les accès pour le support et faire un ticket

**Comment by AliceChiappero** [comment]
@manu-macymed bon on galère pour retrouver le purchase code et les accès, si jamais tu as sous la main ? merci

**Comment by manu-macymed** [comment]
Salut

J'étais en navigation privée car j'étais connectée de l'autre coté, j'imagine bien que tu ne vas pas demandé au client de se mettre en nav privé :). Navigation privée ou non connecté c'est pareil sauf si tu as des extensions qui bloquent certaines exécutions : https://idees-piscine.com/listing-ideep2.mp4
Là en l'occurrence ça marche bien chez moi en non connecté
au cas où :

- https://help.listingprowp.com/
- adeline84
- Latarga!84e

**Comment by AliceChiappero** [comment]
@manu-macymed ok merci pour les accès au support, je vais retester et faire un ticket si besoin

**Comment by manu-macymed** [comment]
@AliceChiappero il y a un souci connu d'incompatibilités entre listingpro et plusieurs modules dont le module de cache. Ca perturbe de temps en temps et c'est pour ça que ça a marché pour moi et que des fois non.
On va voir si on peut gérer ça mais ça va impacter le cache et la vitesse sur les pages de listing. On va faire au mieux

**Comment by manu-macymed** [comment]
@AliceChiappero normalement c'est ok. Tu peux tester en nav privée ou en vidant le cache de ton navigateur. 
C'set lié à ListingPro qui n'aime pas les modules de cache (peu importe le module).

**Comment by AliceChiappero** [comment]
Effectivement marche à présent, merci !
