### ISSUE TITLE
Problème fenêtre de connexion qui mouline

### ISSUE THREAD

**Issue by AliceChiappero** [AliceChiappero/test#25]
Hello,
On a un problème sur la fenêtre de connexion qui mouline
https://app.usebubbles.com/bw3XLVaC3dhBPtfLbT6Eqg
Est-ce que ca peut venir du cache ? ou je dois aussi faire un ticket à listing pro ?
Merci
Bises

**Comment by manu-macymed** [comment]
Salut @AliceChiappero 
On vient de voir qu'il y avait une erreur sur la clés captcha (cf screen). Je pense qu'elle a été révoquée par la personne qui l'avait créée.
On en a recréée une et ça fonctionne de nouveau.

![Image](https://github.com/user-attachments/assets/3e8218f3-db77-45f6-a831-7c4107a1b984)

**Comment by AliceChiappero** [comment]
Je viens de retester en navigation normale et  privée, ca ne marche pas de mon côté 
https://app.usebubbles.com/aiP9tCaYsoppiGfhU4LnKq

**Comment by manu-macymed** [comment]
Il se peut que Google ait mis à jour la gestion des clés et ça n'est pas correctement interprété par ListingPro. On vient de virer la clé captcha sur listingpro et ça fonctionne de nouveau.

**Comment by AliceChiappero** [comment]
et ben voilà, ca venait de là ! ca marche de mon côté aussi :)
Bon je vais dire au client qu'il peut retenter du coup

Merci !

**Comment by manu-macymed** [comment]
Je pense qu'il va falloir qu'on voit pour une alternative définitive à ListingPro car on se rend compte que l'on perd pas mal de temps à cause de ce module (vous et nous). 
Ca n'est pas un petit chantier, loin de là, mais ça nous semble vital. Comme l'ont fait remarquer Yael et Stéphane, c'est une adaptation d'un système qui n'était pas vraiment prévu à cet usage et qui commence à être bloquant pour mettre en place les évolutions.

**Comment by AliceChiappero** [comment]
On est bien d'accord là dessus :) le fait de mettre des pansements en permanence n'est pas la solution...
