### ISSUE TITLE
Mise à jour modules et wp

### ISSUE THREAD

**Issue by dabrokezz** [AliceChiappero/test#3]
Valider les mises à jour sur le staging pour mettre à jour en prod

**Comment by AliceChiappero** [comment]
@dabrokezz on a fait le tour du staging, c'est ok pour nous pour mettre en prod
On a mis à jour JetElements en prod avec la license qu'on avait et j'ai désactivé Slider Revolution sur staging, ca n'a rien cassé dc je vais le désactiver en prod.

**Comment by manu-macymed** [comment]
@AliceChiappero @enileda84 Je viens de mettre à jour en prod (modules et WP). J'ai un peu navigué sur le site, je ne vois aucun dysfonctionnement.
On a accès aux envois d'Elementor à présent.
Si ok pour vous, passez le ticket dans "Done" ;)

**Comment by AliceChiappero** [comment]
@dabrokezz @manu-macymed j'ai fait un tour ça me parait ok, sauf sur la fenêtre de connexion qui mouline qd j'essaie de me connecter, en navigation privée, sur chrome et safari

**Comment by AliceChiappero** [comment]
@dabrokezz @manu-macymed et je viens de voir aussi un pb dans l'affichage de la fenêtre de connexion au BO, voir capture [Image]
(https://github.com/user-attachments/assets/3e226d21-cef8-4740-a601-7ef40758d2e0)

**Comment by manu-macymed** [comment]
> @dabrokezz @manu-macymed j'ai fait un tour ça me parait ok, sauf sur la fenêtre de connexion qui mouline qd j'essaie de me connecter, en navigation privée, sur chrome et safari

J'ai aucun souci là dessus de mon coté. C'est toujours le cas ?

https://macymed.fr/connexion-front.mp4

**Comment by manu-macymed** [comment]
> @dabrokezz @manu-macymed et je viens de voir aussi un pb dans l'affichage de la fenêtre de connexion au BO, voir capture [Image] (https://github.com/user-attachments/assets/3e226d21-cef8-4740-a601-7ef40758d2e0)

pareil, pas de souci de mon coté. C'est en naviguant, à la connexion, autre, ... ?

**Comment by AliceChiappero** [comment]
@manu-macymed pour le 1er point c'est ok, la fenêtre ne mouline plus

Pour le 2eme point, je viens de vérifier et en fait c'est qd tu as une page dans le BO ouverte, que tu te déconnectes et que tu veux te remettre sur cette page, là le formlaire est chelou mais bon c'est pas très grave puisque les autres sont ok

**Comment by dabrokezz** [comment]
Il y avait les 2 problemes :) mais je les ai corrigé (d'ou le fait que @manu-macymed n'ait pas rencontré de problemes

Pour le pb de l'admin, c'est une config et ca devrait plus arrivé
Pour le pb du login (sur le front) c'est un vrai sujet a traiter a part, je crée le ticket (#18)

edit : je vais voir si il reste pas des pages en cache pour l'admin (cf ton reply @AliceChiappero )
