### ISSUE TITLE
Tracking liens sortants

### ISSUE THREAD

**Issue by dabrokezz** [AliceChiappero/test#6]
Mettre en place un système de tracking des liens sortants pour avoir les métriques et avoir plus d'arguments auprès des annonceurs, clients en général

**Comment by dabrokezz** [comment]
Dispo sur staging pour test
https://staging.idees-piscine.com/wp-admin/admin.php?page=macymed_external_clicks&orderby=clicks&order=desc

**Comment by dabrokezz** [comment]
https://github.com/user-attachments/assets/90e21cc4-13c5-4422-915d-bbbfdbfef1c7

**Comment by dabrokezz** [comment]
Bon, listing pro pose encore pb
du dans l'encart de droite (le widget de listing pro) je suis obligé de le gérer en javascript, de recuperer le lien, le supprimer et le remettre, super pratique
Mais au final ca marche

A tester

**Comment by dabrokezz** [comment]
en attente de validation sur staging avant de passer en prod

**Comment by AliceChiappero** [comment]
@dabrokezz Hello, ca a l'air top en regardant la vidéo :) en revanche dans mon BO sur le staging je ne vois pas l'onglet Macymed Click Externes 
![Image](https://github.com/user-attachments/assets/cfacfc30-c285-4ee2-8524-eb4f45d5b848)
donc compliqué de checker :)

**Comment by dabrokezz** [comment]
Salut
@AliceChiappero  en fait avec le pb de stripe et listing pro, le support a désactivé tous les modules, donc on traite stripe et après on remettra tout, 
Désolé

**Comment by AliceChiappero** [comment]
ah mais oui, pas de soucis!

**Comment by AliceChiappero** [comment]
Hello @dabrokezz 
j'ai enfin testé le tracking est ça a l'air de marcher correctement :) dc ok pour passer en prod
Juste une question, peut-on changer le wording  "Redirection vers la page https//www..." en "Vous allez être redirigé vers le site https//www..." ?
merci
